# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 970ca8b74ab9777cba27d594d328f8add1ceee99188d901c47228e5d5767a165cbf145bdd53f33d99d7414983689c43dec668c8132028ab9046cfb0b534693ef

test:
  secret_key_base: 9fd0f8ac9185dc47e06150c66f76b00c84d75007be3389b546e6e53a68644332d30e07974c3f4122aaa340195d4df9998d0e249f4580c5f3b1ba13f811750d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
